version: '3.8'

networks:
  mongo-cluster:

services:
  mongodb1:
    container_name: mongodb1
    image: mongo
    command: mongod --replSet rs0
    ports:
      - 30001:27017
    volumes:
      - mongodb1-data:/data/db
    networks:
      - mongo-cluster

  mongodb2:
    container_name: mongodb2
    image: mongo
    command: mongod --replSet rs0
    ports:
      - 30002:27017
    volumes:
      - mongodb2-data:/data/db
    networks:
      - mongo-cluster

  mongodb3:
    container_name: mongodb3
    image: mongo
    command: mongod --replSet rs0
    ports:
      - 30003:27017
    volumes:
      - mongodb3-data:/data/db
    networks:
      - mongo-cluster

  setup:
    image: mongo
    command: >
      bash -c '
        sleep 10;
        mongosh mongodb1:27017/admin --eval "
          rs.initiate({
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongodb1:27017\," },
              { _id: 1, host: \"mongodb2:27017\," },
              { _id: 2, host: \"mongodb3:27017\," }
            ]
          })
        "
      '
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3

volumes:
  mongodb1-data:
  mongodb2-data:
  mongodb3-data:
